site_name: emodpy-workflow
site_url: https://emod-hub.github.io/emodpy-workflow/
repo_name: EMOD-Hub/emodpy-workflow
repo_url: https://github.com/EMOD-Hub/emodpy-workflow/
edit_uri: tree/main/docs/ # path to the docs folder in your repo

theme:
  name: material
  custom_dir: docs/customization/overrides
  font: 
    text: Roboto
    code: Roboto Mono
  logo: images/EMOD_logo.png
  favicon: images/favicon.ico
  features:
    # - navigation.footer
    - content.code.copy
    - navigation.indexes  # enable parent index page for sections
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: white
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: light blue

nav:  # Navigation structure for the documentation
  - Home: index.md  # the rest of the nav illustrates a typical doc structure
  - installation.md  # including the topic title is optional
  - Reference:
    - reference/virtual_environments.md
    - reference/commands.md
    - reference/projects.md
    - reference/frames.md
    - reference/sweeps.md
    - reference/dtktools_comparison.md
    - reference/age_bin_format.md
    - reference/ingest_form.md
  - How-to:
    - how_to/how_to_make_project.md
    - how_to/how_to_create_frame.md
    - how_to/how_to_use_elements_in_frame.md
    - how_to/how_to_list_hyperparameters.md
    - how_to/how_to_run.md
    - how_to/how_to_calibrate_frame.md
    - how_to/how_to_sweep.md
    - how_to/how_to_download_data.md
    - how_to/how_to_ingest_form.md
    - how_to/how_to_publish_new_country_model.md
  - Tutorials: # this creates a section in the TOC
    - tutorials/get_started.md
    - tutorials/setup.md
    - tutorials/create_project.md
    - tutorials/run_emod.md
    - tutorials/modify_reports.md
    - tutorials/modify_configuration.md
    - tutorials/modify_campaign_1_minimal_campaign.md
    - tutorials/modify_campaign_2_add_vaccine.md
    - tutorials/modify_campaign_3_modify_country_model.md
    - tutorials/use_parameterized_calls.md
    - tutorials/sweep_parameter.md
    - tutorials/run_calibration.md
    #- Get Started: tutorials/intro.ipynb # the topic following index.md sometimes requires an explicit title
  #- Glossary: glossary.md
  # API Reference will automatically be generated and added to the TOC

plugins:
  - search:
  - autorefs:
  - include-markdown:
  - table-reader:  # enables rendering of CSV/TSV files as tables
  - mkdocs-jupyter:  # enables Jupyter notebooks to be rendered
      execute: true
      allow_errors: false  # set to true to continue executing cells even if one fails
      include_source: true

markdown_extensions:
  - admonition:
  - attr_list:  # enables HTMl and CSS classes to inline elements
  - def_list:
  - toc:
      toc_depth: 3
  - md_in_html:  # enables grids
  - pymdownx.arithmatex:  # Latex processing for math equations
      generic: true
  - pymdownx.blocks.caption:  # captions for images, tables, etc.
  - pymdownx.blocks.details:  # allows nesting of collapsible code
  - pymdownx.caret:  # superscripts
  - pymdownx.details:  # collapsible elements
  - pymdownx.emoji:  # emojis and icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:  # syntax highlighting for code blocks
      linenums: true  # adds line numbers to code blocks automatically
      anchor_linenums: true  # adds HTML anchors (#L1, #L2, etc.) to each line so you can link to specific ones.
      default_lang: 'python'
  - pymdownx.inlinehilite:  # syntax highlighting for inline code
  - pymdownx.mark:  # text highlighting
  - pymdownx.snippets:  # snippet reuse functionality
      auto_append:
        - docs/bib.md
  - pymdownx.superfences:  # enables code, diagram fences to be nested in lists, etc.e
  - pymdownx.tabbed: # tabbed content that can be toggled
      alternate_style: true
  - pymdownx.tilde:  # subscripts

copyright: Copyright &copy; 2025 Gates Foundation. All rights reserved.

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - customization/css/extra.css

extra:
  generator: false  # Removes acknowledgement of mkdocs-material
  footer_links:
    - text: "Privacy and Cookies Notice"
      href: "https://www.gatesfoundation.org/Privacy-and-Cookies-Notice"
    - text: "Terms of Use"
      href: "https://www.gatesfoundation.org/Terms-of-Use"
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EMOD-Hub/
    - icon: fontawesome/regular/envelope
      link: mailto:idm@gatesfoundation.org
    - icon: octicons/globe-24
      link: https://idmod.org
    - icon: simple/youtube
      link: http://www.youtube.com/@institutefordiseasemodelin1987
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/institute-disease-modeling
    - icon: fontawesome/brands/slack
      link: https://gatesfoundation.enterprise.slack.com/
  analytics:
    provider: custom
    property: GTM-NK4K647
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you like, provide additional information by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://app.smartsheet.com/b/form/ec8dbb77809949ecab7286a5ca74a206" target="_blank" rel="noopener">feedback form</a>.
